### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by ghost** [peterborodatyy/medusa-plugin-elasticsearch#1]
Hi! thank you for the contribution. 

Is this repo being maintained? what's the status of the plugin? Is there a reason why it's not shown on [medusa](https://medusajs.com/plugins/)?

**Comment by peterborodatyy** [comment]
Hi, sure, it's working & shown on medusa: https://medusajs.com/plugins/medusa-plugin-elasticsearch/

If you have any ideas or suggestions - I'm happy to help!
