### ISSUE TITLE
Issue when testing the plugin with elasticsearch running on host

### ISSUE THREAD

**Issue by amo1101** [peterborodatyy/medusa-plugin-elasticsearch#2]
Hi,

I tried the plugin following the guide, but seems some error occurs when starting medusa backend, index cannot be created:
...
info:    Processing SEARCH_INDEX_EVENT which has 1 subscribers
error:   An error occurred while processing SEARCH_INDEX_EVENT: TypeError: Cannot read properties of undefined (reading 'PRODUCTS')
...

the plugin configuration is the same with the guide but only differs for the config part:
      resolve: `medusa-plugin-elasticsearch`,
      options: {
       config: {
         node: process.env.ELASTICSEARCH_HOST  << http://localhost:9200 from .env
      },

elasticsearch version: 7.10.0
medusa version: latest

The medusa backend and the default storefront end are running normally, and there are seeded products.

Can you help to check what might be the reason?

**Comment by peterborodatyy** [comment]
Hi, can you provide your plugin configuration which you used in `medusa-config.js`?
